Repository libtom/libtomcrypt, pull requests merged in 2018-03, with the labels that each got.

#353 Minor improvements
  doc/crypt.tex
  libtomcrypt_VS2008.vcproj
  makefile.mingw
  makefile.msvc
  makefile.unix
  makefile_include.mk
  src/headers/tomcrypt_custom.h
  src/headers/tomcrypt_misc.h
  src/headers/tomcrypt_pk.h
  src/misc/base16/base16_decode.c
  src/misc/base16/base16_encode.c
  src/misc/base32/base32_decode.c
  src/misc/base32/base32_encode.c
  src/misc/crypt/crypt.c
  src/pk/asn1/x509/x509_decode_subject_public_key_info.c
  src/pk/asn1/x509/x509_encode_subject_public_key_info.c
  tests/base16_test.c
  tests/base32_test.c
  tests/base64_test.c
  tests/common.c
  tests/common.h
  tests/der_test.c
  tests/dh_test.c
  tests/dsa_test.c
  tests/file_test.c
  tests/misc_test.c
  tests/mpi_test.c
  tests/rsa_test.c
  tests/tomcrypt_test.h
Labels: bug, enhancement, improve API

#341 Review of prngs
  doc/crypt.tex
  src/headers/tomcrypt_prng.h
  src/prngs/chacha20.c
  src/prngs/fortuna.c
  src/prngs/rc4.c
  src/prngs/rng_make_prng.c
  src/prngs/sober128.c
  src/prngs/yarrow.c
  tests/prng_test.c
Labels: enhancement

#343 Add padding/depadding support
  demos/openssl-enc.c
  doc/crypt.tex
  libtomcrypt_VS2008.vcproj
  makefile.mingw
  makefile.msvc
  makefile.unix
  makefile_include.mk
  src/headers/tomcrypt_custom.h
  src/headers/tomcrypt_misc.h
  src/misc/crypt/crypt.c
  src/misc/crypt/crypt_constants.c
  src/misc/padding/padding_depad.c
  src/misc/padding/padding_pad.c
  tests/misc_test.c
  tests/padding_test.c
  tests/tomcrypt_test.h
Labels: feature

#366 base64 - use `char *` for Base64 strings
  demos/tv_gen.c
  doc/crypt.tex
  src/headers/tomcrypt_misc.h
  src/misc/base64/base64_decode.c
  src/misc/base64/base64_encode.c
  tests/base64_test.c
  tests/der_test.c
  tests/dsa_test.c
  tests/rsa_test.c
Labels: enhancement

#359 ltc: ctr: improve performance
  src/modes/ctr/ctr_encrypt.c
Labels: enhancement

#368 Improve base16
  doc/crypt.tex
  src/headers/tomcrypt_misc.h
  src/misc/base16/base16_decode.c
  tests/base16_test.c
Labels: enhancement

#369 Add aesgcm demo
  .gitignore
  demos/aesgcm.c
  demos/gcm-file/gcm_file.c
  demos/gcm-file/gcm_filehandle.c
  makefile_include.mk
Labels: feature

#365 Make base64_decode relaxed mode less relaxed
  doc/crypt.tex
  src/headers/tomcrypt_misc.h
  src/misc/base64/base64_decode.c
  tests/base64_test.c
Labels: bug
